import "@/styles/globals.css";
import SessionProvider from "./sessionProvider";
import { Toaster } from "sonner";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Toaster richColors position="top-right" />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}




